---

- name: Create config directory
  ansible.builtin.file:
    path: "{{ config_dir }}/Debauchee"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0775'
  when: not debug

- name: Template Barrier config
  ansible.builtin.template:
    src: "{{ template }}/{{ barrier_role }}/Barrier.conf.j2"
    dest: "{{ config_dir }}/Debauchee/Barrier.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0664'
  when: not debug