---
# Get the Other node's IP, May have more than 2 for multi-monitor!
- name: Get Client IP
  set_fact:
    client_hostname: "{{ hostvars[item]['ansible_all_ipv4_addresses'][interface_num_client] }}"
  with_items: "{{ groups['barrier_client'][0] }}"
  when: barrier_role == "server"

- name: Get Server IP
  set_fact:
    server_hostname: "{{ hostvars[item]['ansible_all_ipv4_addresses'][interface_num_server] }}"
  with_items: "{{ groups['barrier_server'][0] }}"
  when: barrier_role == "client"


# - name: get
#   include_tasks: "dbg.yml"
#   when: debug

# Alternate:
    # client_ip: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"